
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: bushsvc
spec:
  selector:
    app: bushapp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31000
