
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocdd
  name: bushingress
  labels:
    name: bushingress
spec:
  ingressClassName: nginx
  rules:
  - host: enohrose.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bushsvc
            port:
              number: 80




